# Generated by Django 5.0.3 on 2024-03-30 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('birth', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('birth', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.employer')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('itemMedicine', models.IntegerField()),
                ('medicineName', models.CharField(max_length=30)),
                ('medicineDose', models.CharField(max_length=30)),
                ('durationMedication', models.CharField(max_length=30)),
                ('medicineCost', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticHelp',
            fields=[
                ('id', models.AutoField(default=2, primary_key=True, serialize=False)),
                ('itemDiagnostic', models.IntegerField()),
                ('nameDiagnostic', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('diagnosticCost', models.FloatField()),
                ('requiresSpecialistD', models.BooleanField()),
                ('specialistId', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalAppointment',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('doctor', models.CharField(max_length=30)),
                ('appointmentType', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('insuaranceCompany', models.CharField(max_length=30)),
                ('policynumber', models.CharField(max_length=30)),
                ('statePolicy', models.CharField(max_length=30)),
                ('termPolicy', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('doctorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.employer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('itemProcedure', models.IntegerField()),
                ('nameProcedure', models.CharField(max_length=30)),
                ('numberRepeated', models.CharField(max_length=30)),
                ('frequencyRepeated', models.CharField(max_length=30)),
                ('procedureCost', models.FloatField()),
                ('requiresSpecialistP', models.BooleanField()),
                ('specialistId', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
            ],
        ),
    ]
