# Generated by Django 5.0.3 on 2024-04-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='doctorId',
            new_name='doctor',
        ),
    ]
