# Generated by Django 5.0.3 on 2024-04-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_rename_insuarancecompany_policy_insurancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalappointment',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clinicalappointment',
            name='hour',
            field=models.CharField(max_length=30),
        ),
    ]
