# Generated by Django 5.0.3 on 2024-04-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_alter_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
