# Generated by Django 5.0.3 on 2024-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_alter_emergencycontact_id_alter_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalappointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
