# Generated by Django 5.0.3 on 2024-04-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0005_alter_clinicalappointment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='itemMedicine',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='order',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
