# Generated by Django 5.0.3 on 2024-04-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0006_remove_medicine_itemmedicine_remove_medicine_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='itemProcedure',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='order',
        ),
    ]
