# Generated by Django 5.0.3 on 2024-04-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0007_remove_procedure_itemprocedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
