# Generated by Django 5.0.3 on 2024-04-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0008_alter_procedure_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostichelp',
            name='itemDiagnostic',
        ),
        migrations.RemoveField(
            model_name='diagnostichelp',
            name='order',
        ),
        migrations.AlterField(
            model_name='diagnostichelp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
