# Generated by Django 5.0.3 on 2024-04-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0008_billing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
