# Generated by Django 5.0.3 on 2024-04-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0009_remove_diagnostichelp_itemdiagnostic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostichelp',
            old_name='nameDiagnostic',
            new_name='diagnosticName',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='nameProcedure',
            new_name='procedureName',
        ),
    ]
