# Generated by Django 5.0.3 on 2024-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0010_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateField(max_length=30),
        ),
    ]
