# Generated by Django 5.0.3 on 2024-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0011_rename_policynumber_policy_policynumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameSpecialist', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
