# Generated by Django 5.0.3 on 2024-05-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0011_alter_billing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='termPolicy',
            new_name='StatePolicy',
        ),
    ]
