# Generated by Django 5.0.3 on 2024-05-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0012_rename_termpolicy_billing_statepolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='StatePolicy',
            new_name='statePolicy',
        ),
    ]
