# Generated by Django 5.0.3 on 2024-04-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0013_alter_procedure_specialistid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='specialistId',
            new_name='specialist',
        ),
    ]
