# Generated by Django 5.0.3 on 2024-04-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0014_rename_specialistid_procedure_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostichelp',
            name='specialistId',
        ),
        migrations.AddField(
            model_name='diagnostichelp',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.specialist'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.specialist'),
        ),
    ]
